Gitignore Intellij IDEA related files
wso2/dcos-apim pull request #3
Opened 2018-01-30 05:23 UTC by msmshariq

## Purpose
Add Intellij IDEA metafiles files to .gitignore

## Goals
Prevent Intellij IDEA specific files from being tracked by git.

2018-01-30 05:27 UTC, DilanUA requested changes

2018-01-30 05:27 UTC, DilanUA commented on .gitignore
> +target/
Enter new line after this line to avoid this "RED-Symbol".

2018-01-30 05:34 UTC, DilanUA requested changes

2018-01-30 05:34 UTC, DilanUA commented on .gitignore
> +*.iml
.imls are usually inside .idea, so I think *.iml is redundant

2018-01-30 05:43 UTC, DilanUA requested changes

2018-01-30 05:43 UTC, DilanUA commented on .gitignore
> +target/
Let's remove target/ as well since we are not building any sources here, WDYT?

2018-02-07 09:56 UTC, imesh approved these changes

2018-02-07 10:38 UTC, DilanUA approved these changes

2018-02-07 10:38 UTC, merged